### ISSUE TITLE
Unable to write the image on a 64 GB SD Card.

### ISSUE THREAD

**Issue by theheadturner** [vietanhdev/open-adas#8]
Hey Veit Anh,

I tried to write the image on a 64 GB SD Card as the image size is 59.4 GB after extraction. Not successful. Need for an 128 GB ?

I was using BalenaEtcher for writing the image.

Any way out. Pl help.

**Comment by vietanhdev** [comment]
Hello.
I don't know exactly why you could not write the image.
Maybe because of the difference between the real size of 64GB cards from different manufactures.
You can try again with an SD card from Sandisk or Install the components from scratch. It's maybe better because the version of code I have here is newer than the one in the SD card image.
